version: '3.4'

services:
  react-todo:
    container_name: react-todo_dev
    build:
      args:
        - NODE_ENV='development'
        - REACT_APP_NODE_ENV='development'
      context: .
      dockerfile: Dockerfile
      target: development
    image: react-todo_dev
    entrypoint: [ "/bin/sh", "./src/scripts/entrypoint.sh" ]
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV='development'
      - REACT_APP_NODE_ENV='development'
    restart: always
    ports:
      - 3000:3000
